name: mario_bc_env  # Replace with your desired environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.2
  - gym=0.25.2
  - setuptools=41.2.0
  - numpy
  - pandas
  - plotly
  - nbformat
  - kaleido
  - scikit-learn
  - matplotlib
  - stable-baselines3
  - gymnasium
  - opencv
  - optuna
  - tensorboard
  - scipy
  - pip
  - pip:
      - gym-retro==0.8.0